# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "hello/go.sum" }}
      - run:
          name: Install Dependencies
          command: cd hello/ && go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "hello/go.sum" }}
          paths:
            - "/hello/go/pkg/mod"
#      - run:
#          name: Run tests
#          command: |
#            cd hello && mkdir -p /tmp/test-reports
#            cd hello && gotestsum --junitfile /tmp/test-reports/unit-tests.xml
#      - store_test_results:
#          path: /hello/tmp/test-reports

